---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: "${APP}"
spec:
  compression:
    compressor: zstd
  mover:
    cache:
      capacity: "${KOPIUR_CACHE_CAPACITY:=2Gi}"
      mode: Persistent
      storageClassName: "${KOPIUR_STORAGECLASS:=ceph-block}"
    securityContext:
      runAsUser: ${KOPIUR_PUID:=1000}
      runAsGroup: ${KOPIUR_PGID:=1000}
  repository:
    kind: ClusterRepository
    name: garage
  retention:
    keepHourly: 24
    keepDaily: 7
  sources:
    - pvc:
        name: "${CLAIM:-${APP}}"
  volumeSnapshotClassName: "${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}"
