---
# Semantic Type
- name: type/digest
  color: "ffec19"
- name: type/patch
  color: "ffec19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# Uncategorized
- name: hold/upstream
  color: "ee0701"
