---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app configarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      configarr:
        type: cronjob
        cronjob:
          schedule: "0 6 * * *"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/raydak-labs/configarr
              tag: 1.31.0@sha256:ae97eb6eb4009bbbe81a754e7b6e8d33608443c1353b3a1197c55a8ff3e989fa
            env:
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: sonarr-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    persistence:
      config:
        type: configMap
        name: configarr-config
        globalMounts:
          - subPath: config.yml
            path: /app/config/config.yml
