---
apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  annotations:
    external-dns.kubernetes.io/hostname: syslog.smbonn.me
    lbipam.cilium.io/ips: 192.168.10.97
    gatus.home-operations.com/endpoint: |-
      group: services
      url: http://alloy.monitoring.svc.cluster.local:12345/-/ready
      conditions: ["[STATUS] == 200"]
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy
  ports:
    - name: syslog-tcp
      port: 514
      targetPort: 1514
      protocol: TCP
    - name: syslog-udp
      port: 514
      targetPort: 1514
      protocol: UDP
    - name: syslog5424-udp
      port: 515
      targetPort: 1515
      protocol: UDP
