---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/cdi.kubevirt.io/cdi_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    podResourceRequirements:
      limits:
        memory: 2Gi
      requests:
        memory: 60M
    scratchSpaceStorageClass: openebs-hostpath
