---
# yaml-language-server: $schema=https://cluster-schemas.smbonn.me/k8s.mariadb.com/backup_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 2 * * *"
    suspend: false
  timeZone: America/New_York
  compression: zstd
  maxRetention: 720h # 30 days
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  storage:
    s3:
      bucket: mariadb
      endpoint: garage.storage.svc.cluster.local:3900
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: mariadb-backup-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-backup-secret
        key: AWS_SECRET_ACCESS_KEY
      tls:
        enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
