---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-secret
    template:
      engineVersion: v2
      data:
        mariadb-root-password: "{{ .MARIADB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: mariadb
---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-bookstack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookstack-secret
    template:
      engineVersion: v2
      data:
        bookstack-mariadb-password: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
  dataFrom:
    - extract:
        key: bookstack
---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-ptero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pterodactyl-secret
    template:
      engineVersion: v2
      data:
        pterodactyl-mariadb-password: "{{ .PTERODACTYL_MARIADB_PASSWORD }}"
  dataFrom:
    - extract:
        key: pterodactyl
