---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/k8s.mariadb.com/user_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: pterodactyl
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: pterodactyl-secret
    key: pterodactyl-mariadb-password
  maxUserConnections: 20
