---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: pterodactyl
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: pterodactyl-secret
    key: pterodactyl-mariadb-password
  maxUserConnections: 20
