---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    template:
      data:
        HEARTBEAT_URL: "{{ .AM_HEALTHCHECKS_HEARTBEAT_URL }}"
        DISCORD_WEBHOOK: "{{ .AM_DISCORD_WEBHOOK }}"
  dataFrom:
    - extract:
        key: alertmanager
