---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/k8s.mariadb.com/grant_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: bookstack
  namespace: databases
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: bookstackapp
  table: "*"
  username: bookstack
