---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: pterodactyl
  namespace: databases
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: panel
  table: "*"
  username: pterodactyl
