---
sonarrEnabled: true
radarrEnabled: false
lidarrEnabled: false
readarrEnabled: false
whisparrEnabled: false

sonarr:
  instance1:
    base_url: http://sonarr.media
    api_key: !env SONARR__API_KEY

    delete_unmanaged_quality_profiles:
      enabled: true
    delete_unmanaged_custom_formats:
      enabled: true

    quality_profiles:
      - name: "Any"
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: false
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Remux-Bluray-Web-2160p
            qualities:
              - Bluray-2160p Remux
              - Bluray-2160p
              - WEBDL-2160p
              - WEBRip-2160p
              - HDTV-2160p
          - name: Remux-Bluray-Web-1080p
            qualities:
              - Bluray-1080p Remux
              - Bluray-1080p
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p

    custom_formats:
      - trash_ids:
          - 69aa1e159f97d860440b04cd6d590c4f
        assign_scores_to:
          - name: Any
