---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  chartRef:
    kind: OCIRepository
    name: mariadb-operator
  interval: 30m
  values:
    crds:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      certificate:
        certManager: true
      serviceMonitor:
        enabled: true
