[env]
# File paths
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"

[tools]
"github:home-operations/flate" = "0.6.5"
"github:mitsuhiko/minijinja" = "2.24.0"
gum = "2.0.1"
helm = "4.3.0"
helmfile = "1.8.0"
jq = "1.8.2"
just = "1.58.0"
kubeconform = "0.8.0"
kubectl = "1.37.1"
kustomize = "5.8.1"
talos = "1.14.1"
yq = "4.53.6"
