---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
  interval: 1h
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        log:
          rotation:
            enabled: false
        nodePlugin:
          priorityClassName: system-node-critical
          resources:
            plugin:
              limits:
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
            registrar:
              limits:
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
        controllerPlugin:
          priorityClassName: system-cluster-critical
          resources:
            attacher:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            omapGenerator:
              limits:
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
            plugin:
              limits:
                memory: 1Gi
              requests:
                memory: 512Mi
            provisioner:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            resizer:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            snapshotter:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
    drivers:
      cephfs:
        enabled: false
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        grpcTimeout: 150
        snapshotPolicy: volumeSnapshot
        log:
          rotation:
            enabled: false
        controllerPlugin:
          replicas: 2
