---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rps-cloudinit
    template:
      engineVersion: v2
      data:
        userdata: "{{ .cloudConfig }}"
  dataFrom:
    - extract:
        key: rps-cloudinit
