---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: rps
spec:
  sourcePVC: rps
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: rps-volsync-secret
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 2Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
