---
apiVersion: v1
kind: Service
metadata:
  name: rps
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    kubevirt.io/vm: rps
  type: LoadBalancer
