---
apiVersion: v1
kind: Service
metadata:
  name: rps
  annotations:
    lbipam.cilium.io/ips: 192.168.10.95
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: hook
      port: 80
      protocol: TCP
      targetPort: 9000
    - name: app
      port: 8080
      protocol: TCP
      targetPort: 3456
  selector:
    kubevirt.io/vm: rps
  type: LoadBalancer
