---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/cdi.kubevirt.io/storageprofile_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: ceph-block
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteOnce
      volumeMode: Block
  cloneStrategy: snapshot
