---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-server
spec:
  source:
    http:
      url: "https://releases.ubuntu.com/26.04/ubuntu-26.04-live-server-amd64.iso"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: ceph-block
