---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur
      namespace: storage
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.27.0@sha256:ba24b88462380fb59a6c7d04c6d9e607e0b6b04e31306592181186bcdab1952b
            env:
              TZ: "America/New_York"
              BASE_URL: https://mealie.smbonn.me
              DB_ENGINE: postgres
            envFrom: *envFrom
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi
    defaultExternalSecretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    externalSecrets:
      main:
        target:
          name: mealie-secret
          template:
            engineVersion: v2
            data:
              # App
              POSTGRES_DB: mealie
              POSTGRES_SERVER: "{{ .POSTGRES_HOST }}"
              POSTGRES_PORT: "5432"
              POSTGRES_USER: "{{ .MEALIE_POSTGRES_USER }}"
              POSTGRES_PASSWORD: "{{ .MEALIE_POSTGRES_PASS }}"
              # Postgres Init
              INIT_POSTGRES_DBNAME: mealie
              INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
              INIT_POSTGRES_USER: "{{ .MEALIE_POSTGRES_USER }}"
              INIT_POSTGRES_PASS: "{{ .MEALIE_POSTGRES_PASS }}"
              INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
              INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        dataFrom:
          - extract:
              key: mealie
          - extract:
              key: cloudnative-pg
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 9000
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Mealie
          gethomepage.dev/icon: mealie.png
          gethomepage.dev/widget.type: mealie
          gethomepage.dev/widget.url: http://mealie.default:9000
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_MEALIE_KEY}}`}}"
          gethomepage.dev/widget.version: "2"
        hostnames:
          - mealie.smbonn.me
        parentRefs:
          - name: envoy-external
            namespace: networking
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
