---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: volsync
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
