---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 1h
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    gatus:
      delayStartSeconds: "5"
      env:
        TZ: America/New_York
      envFrom:
        - secretRef:
            name: &secret gatus-secret
      logLevel: warn
    sidecar:
      kinds:
        httproute:
          enable: true
          auto: true
        service:
          enable: true
    initContainers:
      - name: init-db
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18
        envFrom:
          - secretRef:
              name: *secret
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/enabled: "false"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Observability
        gethomepage.dev/name: Gatus
        gethomepage.dev/icon: gatus.png
        gethomepage.dev/widget.type: gatus
        gethomepage.dev/widget.url: http://gatus.monitoring
      hostnames:
        - status.smbonn.me
      parentRefs:
        - name: envoy-external
          namespace: networking
    monitoring:
      serviceMonitor:
        enabled: true
    config:
      existingConfigMap: gatus-configmap
      items:
        - key: config.yaml
          path: config.yaml
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 512Mi
