---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mysql-backup-secret
    template:
      engineVersion: v2
      data:
        DEFAULT_S3_KEY_ID: "{{ .S3_KEY_ID }}"
        DEFAULT_S3_KEY_SECRET: "{{ .S3_KEY_SECRET }}"
  dataFrom:
    - extract:
        key: mysql-backup
